"""Add tipo_proceso column

Revision ID: 922b5a64e684
Revises: 80bee17cebec
Create Date: 2025-06-09 21:23:52.673419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922b5a64e684'
down_revision: Union[str, None] = '80bee17cebec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eficiencias_fecha'), table_name='eficiencias')
    op.drop_index(op.f('ix_eficiencias_id'), table_name='eficiencias')
    op.drop_index(op.f('ix_eficiencias_linea'), table_name='eficiencias')
    op.drop_index(op.f('ix_eficiencias_nombre_asociado'), table_name='eficiencias')
    op.drop_index(op.f('ix_eficiencias_proceso'), table_name='eficiencias')
    op.drop_index(op.f('ix_eficiencias_turno'), table_name='eficiencias')
    op.drop_index(op.f('ix_eficiencias_wwid'), table_name='eficiencias')
    op.drop_table('eficiencias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eficiencias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_asociado', sa.VARCHAR(), nullable=False),
    sa.Column('wwid', sa.INTEGER(), nullable=False),
    sa.Column('linea', sa.VARCHAR(), nullable=False),
    sa.Column('supervisor', sa.VARCHAR(), nullable=False),
    sa.Column('proceso', sa.VARCHAR(), nullable=False),
    sa.Column('numero_batch', sa.VARCHAR(), nullable=False),
    sa.Column('eficiencia_asociado', sa.FLOAT(), nullable=False),
    sa.Column('eficiencia_linea', sa.FLOAT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('turno', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eficiencias_wwid'), 'eficiencias', ['wwid'], unique=False)
    op.create_index(op.f('ix_eficiencias_turno'), 'eficiencias', ['turno'], unique=False)
    op.create_index(op.f('ix_eficiencias_proceso'), 'eficiencias', ['proceso'], unique=False)
    op.create_index(op.f('ix_eficiencias_nombre_asociado'), 'eficiencias', ['nombre_asociado'], unique=False)
    op.create_index(op.f('ix_eficiencias_linea'), 'eficiencias', ['linea'], unique=False)
    op.create_index(op.f('ix_eficiencias_id'), 'eficiencias', ['id'], unique=False)
    op.create_index(op.f('ix_eficiencias_fecha'), 'eficiencias', ['fecha'], unique=False)
    # ### end Alembic commands ###
